### PR TITLE
Final Application

### PR DESCRIPTION
**Pull request by Yogin94**

### CODE REVIEW

**Comment by Yogin94** [comment]
Work Submitted

**Comment by caiodias** [comment]
Please update your PR to point to https://github.com/caiodias/bootcamp-android-project

**Comment by Yogin94** [comment]
Hey
I am not sure what you want me to do? Can You please explain in easier manner or if you want i can give you my access to git. Thanks again for taking your time into this.
Yogin bhatt

**Comment by shahyash9795** [comment]
What about mine?

Shahyash9795

**Comment by caiodias** [comment]
Why you first commit has 99% of the work instead of the begin of it?

**Comment by Yogin94** [comment]
Hey
Can you tell me exactly what is the issue here and who you talking to because me and yash both getting email

**Comment by caiodias** [comment]
Pay attention on the Pull Request. The email is just a notification. Please verify where it comes from.

**Pull request merged**
