### PR TITLE
Final Changes.

### PR DESCRIPTION
**Pull request by shahyash9795**

### CODE REVIEW

**Comment by caiodias** [comment]
Please update your Pull Request to point to https://github.com/caiodias/bootcamp-android-project

**Comment by shahyash9795** [comment]
Hey caio,

I dont understand what u said..

You can open my account on github.

Email : shahyash9795@gmail.com
Pwd : Shahyash_7

Sorry

**Comment by caiodias** [comment]
@shahyash9795 I deleted your last comment because you **should never** share your credentials in public.

You had changed the colours and strings.xml file. You are not supposed to change the app name and other stuff related to other people project. I can't accept your Pull Request until you fix it.

**Comment by shahyash9795** [comment]
Ok give me some time.
I am checking it now

**Comment by shahyash9795** [comment]
So Do i need to undo changes in strings.xml and colors.xml?

**Comment by caiodias** [comment]
You can do changes on strings.xml and colours.xml files but you to add stuff. **Not** change what is already there like the app name for example. The app name should be the same.

**Comment by shahyash9795** [comment]
Ohhh I did that because of some animation.

So I am undo it.

And then I need to commit it from the sourcetree right?

**Comment by caiodias** [comment]
Yes, whatever is the change that you want to make, you have to commit and then push your commit.

**Comment by shahyash9795** [comment]
Hey caio,

I did not made any changes in colors.xml and strings.xml.


I just made change in style.xml

**Comment by shahyash9795** [comment]
When I connected firebase to my app then it automatically adds some lines
in strings.xml


I did not know about that

**Comment by shahyash9795** [comment]
Does the app name was the ‘blog’ before?
In strings.xml?
Can you tell me please

**Comment by caiodias** [comment]
Yes and no. Yes, because I made a mistake before where I accept a Pull Request that changed it but no because it should have another name :)

I will fix it soon.

**Comment by shahyash9795** [comment]
ok I am solving strings.xml file and will commit again from sourcetree.

**Comment by shahyash9795** [comment]
Hey caio,
I solved Strings.xml and colors.xml.
Can you tell me now is it eligible to merge or not?

**Comment by caiodias** [comment]
Now is okay, thank you.

**Comment by shahyash9795** [comment]
Thanks a lot...
appreciate for your time and help.
thanks a lot again

**Comment by shahyash9795** [comment]
Is there anything that I need to do from my side?

**Comment by shahyash9795** [comment]
Thank you caio.

**Pull request merged**
